### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by jpmachikid** [jpmachikid/protospace-39492#1]
https://protospace-39492.onrender.com/

**Comment by motomuun** [comment]
@jpmachikid さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）

**Comment by jpmachikid** [comment]
早速のご確認ありがとう御座いました！
